### ISSUE TITLE
请问一下您的这个项目怎么运行呢？

### ISSUE THREAD

**Issue by ArrayCat7** [ASh-en/MissileCombat#1]
您好，我克隆了您的项目，但是不知道怎么运行，可以说明一下吗？谢谢！

**Comment by ASh-en** [comment]
我已经更新了一下Readme了，当然如果是飞机类飞行器的可以看closeaircombat项目，我的也是从他的基础上改的，导弹类的可能需要自己提供相关的空气动力学参数文件（JSBSim的xml格式文件），后续我可能会上传一个工具，可以通过飞行器的外形计算生成符合条件的xml文件(目前测试还有问题)。当然，如果你能有风洞试验的数据自然是最好的。

**Comment by ArrayCat7** [comment]
请问您这边有可以用的弹类xml文件吗？

另外想请教一下，比如发射这个动作是在动作空间里设置吗？像这种不是类似操纵杆控制量那种每一个step都会用到的动作，怎么去设计动作空间比较合理呢？

感谢！

**Comment by ASh-en** [comment]
个人认为关于发射动作的话，需要考虑我们的具体任务是什么。一般而言在发射前，考量的是如何选择发射时间，发射后则是考虑如何控制导弹姿态等操作。这应该是两个独立的动作空间，可以通过两个任务进行训练，当然你可以将其设计到同一个训练任务中，不过我觉得采用分层训练可能会更适合。先训练好控制导弹接近目标，然后训练选择发射时间。当然这其中也可以使用已有的导引律的方法。
